### PR TITLE
Fixed error when pushing annotations which contain a `/` in the `id`

### PR DESCRIPTION
**Pull request by lukipro**
If an annotation happens to have a `/` in the `id`, then Bitbucket API responds with the following error:
```
Could not push report to Bitbucket. 404 {"type": "error", "error": {"message": "Resource not found", "detail": "There is no API hosted at this URL.\n\nFor information about our API's, please refer to the documentation at: https://developer.atlassian.com/bitbucket/api/2/reference/"}}
```

For example for `@angular/core`, the url is as follows:
```
<HOST>/2.0/repositories/<OWNER>/<REPO>/commit/<COMMIT>/reports/<REPORT_ID>/annotations/luki6-@angular/core
```

This PR will change the resulting url to:
```
<HOST>/2.0/repositories/<OWNER>/<REPO>/commit/<COMMIT>/reports/<REPORT_ID>/annotations/luki6-@angular-core
```
which is accepted by the Bitbucket API.

### CODE REVIEW

**Comment by saibotsivad** [comment]
Ah yeah, great find, thanks! I'm going to see if I can edit this PR to tidy it, otherwise I'll pull it locally.

**Comment by saibotsivad** [comment]
Apparently I can't drop files from a PR via the web, which is what I thought the "delete" action would do... I'll pull down locally and fix. 🤦‍♂️

**Comment by saibotsivad** [comment]
[v1.4.2](https://github.com/saibotsivad/bpr-npm-audit/releases/tag/v1.4.2) is published to npm.

Thanks again @lukipro !

**Comment by lukipro** [comment]
Thanks for handling this so swiftly @saibotsivad 🍻

**Pull request merged**
